version: "3"
services: 
    mongodb:
        image: mongo
        container_name: mongo
        ports: 
            - 27017
        hostname: mongo
        volumes: 
            - $HOME/mongodb/data/db:/data/db
    helloapp:
        build: 
            context: ../../
            dockerfile: ./Docker/devops/Dockerfile
        image: helloapp
        container_name: helloapp
        ports: 
            - 8080:8080
        hostname: helloapp
        links: 
            - mongodb:mongo
